version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: mongo-local
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  pix-gateway:
    build:
      context: ./pix-gateway
      dockerfile: Dockerfile
    container_name: pix-gateway
    depends_on:
      - mongo
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/challenge
    ports:
      - "8081:8081"
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
