POST http://localhost:8081/api/pix
Content-Type: application/json

{
  "tipoChave": "cpf",
  "valorChave": "12345678802",
  "tipoConta": "corrente",
  "numeroAgencia": "1235",
  "numeroConta": "12345678",
  "nomeCorrentista": "Joao",
  "sobrenomeCorrentista": "Silva",
  "saldo": 1000.00
}
------
{
  "tipoChave": "cpf",
  "valorChave": "12345678801",
  "tipoConta": "corrente",
  "numeroAgencia": "1234",
  "numeroConta": "12345679",
  "nomeCorrentista": "Pedro",
  "sobrenomeCorrentista": "Pascal",
  "saldo": 1000.00
}